name: mlflow-env
channels: 
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip: 
      - mlflow==2.18.0
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - matplotlib
